# Generated by Django 4.2.2 on 2023-06-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('field', models.CharField(max_length=50)),
                ('paper', models.FileField(upload_to='')),
                ('summary', models.TextField(max_length=1000)),
            ],
        ),
    ]
