# Generated by Django 4.2.2 on 2023-06-17 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 17, 21, 35, 1, 269922, tzinfo=datetime.timezone.utc), verbose_name=datetime.datetime(2023, 6, 17, 21, 34, 20, 918656, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
