# Generated by Django 4.2.2 on 2023-06-17 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0003_alter_submission_date_alter_submission_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='summary',
            field=models.TextField(blank=True, editable=False, max_length=1000),
        ),
    ]
