# Generated by Django 4.2.2 on 2023-06-17 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0004_alter_submission_date_alter_submission_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
