# Generated by Django 4.2.2 on 2023-06-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0005_alter_submission_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='endSection',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='startSection',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
